import { ReleaseProps } from "../../types/Releases";

// MOCK INITIAL FIXED RELEASES
export const FIXED_RELEASES_MOCK: ReleaseProps[] = [
  { id: "1", title: "salário", type: "in", category: "emprego", value: 2000 },
  { id: "2", title: "aluguel", type: "out", category: "moradia", value: 700 },
  { id: "3", title: "energia", type: "out", category: "moradia", value: 200 },
  { id: "4", title: "internet", type: "out", category: "moradia", value: 70 },
];
